# Generated by Django 5.1.4 on 2024-12-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmap',
            name='radar_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='r2_channel_map_set', to='radar.radar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channelmap',
            name='radar_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r1_channel_map_set', to='radar.radar'),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('channel_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.channelmap')),
            ],
        ),
        migrations.CreateModel(
            name='RadarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.IntegerField()),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.radar')),
            ],
        ),
    ]
