# Generated by Django 5.1.4 on 2024-12-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0002_channelmap_radar_2_alter_channelmap_radar_1_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
