# Generated by Django 5.1.4 on 2024-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0003_alter_radar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmap',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
