# Generated by Django 5.1.4 on 2024-12-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_alter_channelmap_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='radardata',
            name='is_left',
            field=models.BooleanField(default=False),
        ),
    ]
