# Generated by Django 5.1.4 on 2024-12-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0005_radardata_is_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radardata',
            name='is_left',
        ),
        migrations.AddField(
            model_name='radar',
            name='is_left',
            field=models.BooleanField(default=False),
        ),
    ]
